apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-embed-code-service
  labels:
    app: video-embed-code-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: video-embed-code-service
  template:
    metadata:
      labels:
        app: video-embed-code-service
    spec:
      containers:
        - name: video-embed-code-service
          image: video-embed-code-service:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: "500Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: video-embed-code-service
  labels:
    app: video-embed-code-service
spec:
  type: NodePort
  selector:
    app: video-embed-code-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080